version: '3'

services:

  nginx-front:
    image: 'nginx'
    volumes:
      - C:\IDEA Projects\AuthorizationService\nginx:/usr/share/nginx/html
    container_name: 'html'
    ports:
      - '80:80'
  server:
    build: ./
    image: 'java-authorize'
    container_name: 'my-service'
    ports:
      - '8080:8080'


